"""Prompts package for debate system."""

from prompts.debate_prompts import (
    ARCHITECT_SYSTEM_PROMPT,
    PERFORMANCE_SYSTEM_PROMPT,
    SECURITY_SYSTEM_PROMPT,
    MODERATOR_SYSTEM_PROMPT,
    SCORING_SYSTEM_PROMPT,
    JUDGE_SYSTEM_PROMPT,
    CROSS_EXAMINATION_TEMPLATE,
    ARGUMENT_FORMAT,
    EVALUATION_FORMAT,
    JUDGE_DECISION_FORMAT
)

__all__ = [
    'ARCHITECT_SYSTEM_PROMPT',
    'PERFORMANCE_SYSTEM_PROMPT',
    'SECURITY_SYSTEM_PROMPT',
    'MODERATOR_SYSTEM_PROMPT',
    'SCORING_SYSTEM_PROMPT',
    'JUDGE_SYSTEM_PROMPT',
    'CROSS_EXAMINATION_TEMPLATE',
    'ARGUMENT_FORMAT',
    'EVALUATION_FORMAT',
    'JUDGE_DECISION_FORMAT'
]
